# Generated by Django 4.2.6 on 2023-10-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='imagesofpeople')),
                ('about', models.TextField(default='about')),
            ],
        ),
    ]
